repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black src
        language: system
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 src
        language: system
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c '.venv/bin/pip freeze > requirements.txt; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python3 -m pytest
        language: system
        pass_filenames: false
        stages: [commit]